### ISSUE TITLE
More datasets to add to the wiki

### ISSUE THREAD

**Issue by alevyinroc** [amtwo/Data-Blogger-Resource-Kit#13]
MusicBrainz - https://musicbrainz.org/doc/MusicBrainz_Database/Download

OpenStreetMap - https://wiki.openstreetmap.org/wiki/Planet.osm

Amazon Customer Reviews - https://registry.opendata.aws/amazon-reviews/

GDELT news data - https://registry.opendata.aws/gdelt/

**Comment by amtwo** [comment]
Done (finally)
